name: 'Bytebase Rollout'
description: 'Rollout on Bytebase.'

branding:
  icon: 'database'
  color: 'red'

inputs:
  url:
    description: The bytebase URL.
    required: true
  token:
    description: The Bytebase access token.
    required: true
  plan:
    description:
      'The plan to create the rollout from. Format:
      projects/{project}/plans/{plan}'
    required: true
  target-stage:
    description: >
      Bytebase rollout pipeline can contain multiple stages. This action will
      exit after complete deploying the `target-stage` stage. `target-stage` is
      the stage environment. Example: `prod`

runs:
  using: node20
  main: dist/index.js
